Update build-and-deploy.yml

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -35,13 +35,15 @@ jobs:
 
       - name: Update deployment.yaml
         run: |
+          echo "Updating deployment.yaml..."
           sed -i 's|image: .*/newimage:.*|image: arunazhagappan/newimage:latest|g' deployment.yaml || echo "No deployment.yaml found or no need to update"
-          
+          cat deployment.yaml  # Print the updated deployment.yaml for debugging
         env:
           DOCKER_IMAGE: arunazhagappan/newimage:latest
 
       - name: Commit and push changes
         run: |
+          echo "Committing changes..."
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git add deployment.yaml
@@ -59,6 +61,6 @@ jobs:
         run: |
           echo "Triggering ArgoCD sync..."
           curl -k -X POST https://0d66-117-242-217-241.ngrok-free.app/api/v1/applications/my-app/sync \
-          -H "Authorization: Bearer $ARGOCD_TOKEN" || { echo "Failed to trigger ArgoCD sync"; exit 1; }
+          -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" || { echo "Failed to trigger ArgoCD sync"; exit 1; }
         env:
           ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
