Update build-and-deploy.yml

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -15,6 +15,14 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      # Install ngrok directly (if needed)
+      # - name: Download ngrok
+      #   run: |
+      #     curl -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
+      #     unzip ngrok.zip
+      #     chmod +x ngrok
+      #     sudo mv ngrok /usr/local/bin/ngrok
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
 
@@ -30,21 +38,26 @@ jobs:
           context: .
           file: ./Dockerfile
           push: true
-          tags: arunazhagappan/nginx-image:${{ github.sha }}
+          tags: arunazhagappan/nginx-image:latest
 
-      - name: Substitute environment variables in deployment.yaml
+      - name: Run NGINX container for tests
         run: |
-          envsubst < deployment.yaml > deployment.yaml
-
-      - name: Apply Kubernetes deployment
-        run: |
-          kubectl apply -f deployment.yaml
+          docker run --name nginx-test-container -d -p 8080:80 arunazhagappan/nginx-image:latest
+          sleep 10  # Adjust sleep time based on NGINX startup time
+          response=$(curl -s -I http://localhost:8080/index.html)
+          echo "NGINX Test Response:"
+          echo "$response"
+          echo ""
+          echo "NGINX Test Content:"
+          curl -s http://localhost:8080/index.html
+          docker logs nginx-test-container  # Output logs for debugging
+          docker stop nginx-test-container
+          docker rm nginx-test-container
 
       - name: Trigger ArgoCD sync
         run: |
           echo "Triggering ArgoCD sync..."
           curl -k -X POST https://e952-117-242-217-241.ngrok-free.app/api/v1/applications/my-app/sync \
-          -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
-          || { echo "Failed to trigger ArgoCD sync"; exit 1; }
+          -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" || { echo "Failed to trigger ArgoCD sync"; exit 1; }
         env:
           ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
